USE jugos_ventas;

SELECT * FROM tabla_de_clientes;

SELECT NOMBRE, FECHA_DE_NACIMIENTO,
CASE
    WHEN YEAR(FECHA_DE_NACIMIENTO) <1990 THEN 'Viejos'
    WHEN YEAR(FECHA_DE_NACIMIENTO) BETWEEN 1990 AND 1995 THEN 'Jóvenes'
    ELSE 'Niños'
END AS CLASIFICACION
FROM tabla_de_clientes;
